### ISSUE TITLE
Impossible to see my synology

### ISSUE THREAD

**Issue by pgaudel** [stfnhmplr/homebridge-synology#11]
Hi,

My Homebridge is started without any synology.

When I start my homebridge, I have this :
[2016-09-21 02:33:32] Loaded plugin: homebridge-synology
[2016-09-21 02:33:32] Registering accessory 'homebridge-synology.Synology'
[2016-09-21 02:33:32] ---

I don't understand where is my mistake I added on homebridge config.json my synology like accessories. Can you help me ? 

I have my homebridge on raspberry pi2 and my synology is DS215j version with DSM 6

Thanks in advance

**Comment by rafacampoamor** [comment]
Same problem here with a Pi 3 and DS212j :(

I cannot find the plugin files. Maybe the instalation fails at some point?

**Comment by stfnhmplr** [comment]
Sorry for my late response. Is this still a current problem? Did you install the plugin globally? are there any more error messages? looks like the accessory is registered successfully.
I published an update to npm. maybe you try this first.
