### ISSUE TITLE
NAS without WOL

### ISSUE THREAD

**Issue by D3-Bug** [stfnhmplr/homebridge-synology#13]
My NAS (DS411j) does not support WOL.

Can you add an option that when there is no mac-address, there is no on/off switch?

A second problem I have is that the cpu and disk usage is not showing in HomeKit.

**Comment by mrDeltaKilo** [comment]
Similar problems on DS415+. WOL is not functioning, temperature and CPU use do not appear, and Disk Usage does appear, but it's labeled with degrees and is read as a temperature. I'm going to look into it this evening.

**Comment by stfnhmplr** [comment]
I published an update with a new disable option. you can now disable the switch service.
for your second problem please switch to this issue: https://github.com/stfnhmplr/homebridge-synology/issues/16
