### ISSUE TITLE
Get no response on Home app

### ISSUE THREAD

**Issue by ava8c** [stfnhmplr/homebridge-synology#14]
Hi, I think that home bridge works fine. But when I try to update System Temperature for example I get "updating" then "no Response" on Home iOS 10 app. And in terminal
[NASName] current power state is: false
Could you help me? thanks

**Comment by ava8c** [comment]
Solved changing on no secure. Still get to disk usage and CPU indicator. Some help? thanks

**Comment by stfnhmplr** [comment]
hi. does the port match with the secure option? If you use the default ports: secure=true should be port 5001, secure=false should be port 5000. maybe you can post your config.json here.
there's also an update available via npm. Please close this issue if it's fixed with the update.

**Comment by actuariat** [comment]
I have the same problem, although I set 5000 with false.

**Comment by actuariat** [comment]
"accessory": "Synology",
"name": "NAS",
"ip": "192.168.0.10",
"mac": "00******",
"port": "5000",
"secure": false,
"account": "****",
"password": "*****",
"version": 6

**Comment by actuariat** [comment]
I have done nothing, but:

3/10/2017, 5:35:47 PM] [NAS] current power state is: false
[3/10/2017, 5:35:49 PM] [NAS] An error occured while getting SystemTemp: Can't Login to Diskstation
[3/10/2017, 5:36:35 PM] [NAS] current power state is: false
[3/10/2017, 5:36:43 PM] [NAS] current system temp: 37 °C
[3/10/2017, 5:36:51 PM] [NAS] current power state is: false
[3/10/2017, 5:36:59 PM] [NAS] current system temp: 37 °C

**Comment by actuariat** [comment]
So clearly it connects now, but with problems

**Comment by stfnhmplr** [comment]
thats weird. can you reach the webinterface with http://192.168.0.10:5000?

**Comment by actuariat** [comment]
Yes, it is weird, cause sometimes it works, meaning only 2 accessories:
1. state (can shut down the system)
2. temperature: only one

The link you provided works fine. (Synology works fine)

Mar 11 11:28:52 pi homebridge[663]: [3/11/2017, 11:28:52 AM] [NAS] An error occured while getting SystemTemp: Can't Login to Diskstation
Mar 11 11:28:55 pi homebridge[663]: [3/11/2017, 11:28:55 AM] [NAS] current power state is: false

**Comment by stfnhmplr** [comment]
I have added a timeout option to the config. Please increase the timeout to 10000 or more. Default is 5000. Maybe your Diskstations response is to slow.
For the other characteristics (cpu and disk usage) take a look here: https://github.com/stfnhmplr/homebridge-synology/issues/16 and try the Eve App (free).

**Comment by stfnhmplr** [comment]
@acturiat Does it work when you increase the timeout?

**Comment by actuariat** [comment]
It lookg good now, using Eve gives me all the stats. Great job!
