### ISSUE TITLE
2-step verification

### ISSUE THREAD

**Issue by kuroshirokun** [stfnhmplr/homebridge-synology#18]
Hi, I can't see my Synology, I'm guessing it's because I'm using 2-step verification. I don't plan on removing 2-step verification. Is there still a way I can make this work ?

Regards

**Comment by stfnhmplr** [comment]
hi. you're right. 2fa is not supported yet. the api is not well documented. there is an otp_code but for now i don't know how two generate the code on the fly.
one possibilty is to create an extra user with little rights and disable the 2fa only for this user.
