### ISSUE TITLE
Wrong power status

### ISSUE THREAD

**Issue by Rasket787** [stfnhmplr/homebridge-synology#20]
First of all I would like to say thank you for your work it is realy great. 
But i have a problem with it. The program show that the diskstation is power off but it isn't. If I power on with the app it show power on but when i refreash it shows power off again. 

DS216play DSM 6.1-update 2

**Comment by stfnhmplr** [comment]
Hi. Thank you. 

Would you check your log files please? There should be an error message. 

Can you access the diskstations web interface with the settings in your config.json? 

If this works, please try to increase the timeout in your config.json. Maybe your diskstations response is to slow. 

Does your diskstation support wol? you will not be able to switch it on via homebridge if not.

**Comment by Rasket787** [comment]
I use port 5000 and secure "false". Is it good?
Other functions work well I can see cpu load, system temp and volume usegae in the Eve app and wol is also works.
But I can't see the power status. On the command line I see "current power state is: false"
I try to increase the timeout but nothing happened.

Have you got any idea?

**Comment by stfnhmplr** [comment]
Should be fine if you can reach the webinterface of your diskstation with http://`diskstation_ip`:5000
Actually this must work, since the other values are returned. Did you set the timeout to 10000 or more? this solved https://github.com/stfnhmplr/homebridge-synology/issues/14

**Comment by Rasket787** [comment]
Thank you. Automatic redirecting was active from http to https.  Timeout 5000 is ok. :)
