### ISSUE TITLE
general understanding issue

### ISSUE THREAD

**Issue by Nixontira** [stfnhmplr/homebridge-synology#21]
Hey,
im pretty new in the homebridge scene. Got a few questions about the config.json data

"accessory": "Synology",

"name": "Diskstation",        <--- this just standard no need change or? Just the name that shows up on my device?!

"ip": "192.168.178.1",      <--- This just the ip of my NAS?!

"mac": "A1:B3:C3:D4:E5:EX",     <--- This just the Mac-Adress of my NAS
          
"port": "port number",    <--- Which port is that? is it the 5000 for http or 5001 for https? and which would I have to use?

"secure": false,     <--- is the state "false" standard? or when would I have to change it to true?

"account": "admin",     <--- This just the admin username of my NAS

"password": "supersecret",    <--- This just the admin password of my NAS

"version": 5, //DSM Version, default is 6.       <--- Im using DSM 6.x, so I have to change the 5 to a 6?!

"timeout": 5000, //in ms.   <--- what is this for?

"disabled": ["switch", "temp"].   <--- I would like to have everything turned on. So I should delete those two options u put in there right? How exactly should it look like afterwards?

Im sorry for my noob Knowledge :(

**Comment by Nixontira** [comment]
Okay I got it to work with the settings I named, but how does it show me cpu load and temperature?

**Comment by stfnhmplr** [comment]
Hi. I will add some more infos  to the readme. Did you read https://github.com/stfnhmplr/homebridge-synology/issues/16 ? The additional infos are only displayed at the EVE App for now.
The rooms are managed with the iOS Apps. I can't help here.

**Comment by Nixontira** [comment]
Nope didnt see that yet :/ thanks for the information. too bad apple doesn't support that :/
