### ISSUE TITLE
Question: Diskstation services

### ISSUE THREAD

**Issue by nickbrown20** [stfnhmplr/homebridge-synology#25]
What services have to be enabled on the diskstation to make it work?

**Comment by stfnhmplr** [comment]
Hey,

it should work out of the box. There are no additional service you've to install.

**Comment by stfnhmplr** [comment]
Hey there!

I close this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. If the issue still exists, let me know with a comment and i will reopen it.

Thanks!
