### ISSUE TITLE
Can not display CPU load and DiskUsage

### ISSUE THREAD

**Issue by jnhoii** [stfnhmplr/homebridge-synology#27]
Why my homekit can only show the switch with the temperature, the DiskUsage with the CPU load can not be displayed, and I did not set config.json with disable.

**Comment by rgerr** [comment]
Same issue, Home app does not show diskusage and cpu load. It does show temperature, but stays in 0 degrees however.

**Comment by Krocko** [comment]
The same for me. Any solution?

**Comment by mbakker96** [comment]
Same problem here. Home kit says that my NAS is turned off and that the temperature is zero degrees. I know I've cool content on that NAS but not that cool.. ;)

**Comment by m42e** [comment]
Just try to use http instead of https, worked for me. Seems the plugin does not handle invalid certificates well.

**Comment by stfnhmplr** [comment]
There is a ssl branch in this repository. I can't test it. Maybe you can clone the ssl branch to your homebridge setup and test it. This should work with the invalid certificates. Any Feedback is welcome.

**Comment by Razeeer** [comment]
@m42e 

> Just try to use http instead of https, worked for me. Seems the plugin does not handle invalid certificates well.

How did you change that exactly on your DiskStation?

**Comment by Nastras** [comment]
I also had the problem, it is important that the user is a member of the Admin group in DSM. Since then it works for me.

**Comment by mbierman** [comment]
Doesn't work for me even as a user in the admin group.
