### ISSUE TITLE
run this

### ISSUE THREAD

**Issue by vespino** [stfnhmplr/homebridge-synology#28]
I have looked into this for a way to use siri in combination with domoticz: https://www.domoticz.com/wiki/Homekit_Siri. A while ago I got this running on a Raspberry Pi without problems, but since I'm running domoticz on a synology diskstation, this will probably work differently. I have installed homebridge-synology, but can you tell me how to run it?

**Comment by stfnhmplr** [comment]
This plugin controls your diskstation, it does not help you to install homebridge on the diskstation. Maybe you can use a docker image? But I can't help here.
