### ISSUE TITLE
current power state is: false

### ISSUE THREAD

**Issue by m4d-maNu** [stfnhmplr/homebridge-synology#29]
Hi,
my power state is always false.... i use DSM 6.1.4-15217 Update 2, need the synology plugin an update with a new API? Or I have a wrong config?

	{
            "accessory": "Synology",
            "name": "DiskStation",
            "ip": "xxx",
            "mac": "xxx",
            "port": "5000", 
            "secure": "false", 
            "account": "xxx",
            "password": "xxx,
            "version": "6",
            "timeout": "10000",
            "disabled": "switch",
            "doPolling": "true",
            "pollingInterval": "60"
        }

xxx is changed with my dates

**Comment by MikeDeltaHH** [comment]
Have the same problem after update my Sonology to DSM 6.1.4-15217 Update 5... any idea?

**Comment by stfnhmplr** [comment]
The config looks fine except for the disabled property. Don't disable the switch.
