### ISSUE TITLE
Shutdown and power on works. Temperature, CPU load and Disk usage don't

### ISSUE THREAD

**Issue by fcrespo82** [stfnhmplr/homebridge-synology#33]
Itens show on Eve app, but everything is zero.

Power show correctly and I can power on and shutdown the NAS.

homebridge version: 0.4.38
homebridge-synology version: 0.3.0

config.js - removed sensitive information
```
{
     "secure" : false,
     "version" : 6,
     "timeout" : 5000,
     "port" : "8020",
     "account" : "admin",
     "name" : "NAS",
     "ip" : "nas.house.crespo",
     "accessory" : "Synology"
}
```

How to troubleshoot? Nothing appears in the logs

**Comment by johnsills1** [comment]
I'm having the same issue. 

Do I have to install the 4 dependencies listed on my Homebridge?

**Comment by ak-media** [comment]
Same here, works fine but no CPU load and Disk Usage…

**Comment by ultraflorescence** [comment]
+1

**Comment by Nastras** [comment]
I also had the problem, it is important that the user is a member of the Admin group in DSM. Since then it works for me.

**Comment by ultraflorescence** [comment]
That's odd, it didn't work for me.

**Comment by fcrespo82** [comment]
Didn't work for me either, and I am using the admin user!

**Comment by Nastras** [comment]
Please use the same config as me.
If I remember correctly, it worked after I added part of the option.

"version": 6,
"timeout": 5000,
"disabled": [],
"doPolling": true,
"pollingInterval": 60

**Comment by ultraflorescence** [comment]
That did the trick! Thanks

**Comment by fcrespo82** [comment]
"doPolling": true,
"pollingInterval": 60

Made it work again! Thanks for the help!

**Comment by Nastras** [comment]
Cool, that makes me happy 😉👍

**Comment by DutchmanNL** [comment]
having the same issue, only power off is shown in homebridge
adjusted my config with the suggested lines but still only the on/off button is shown nothing else.

DSM version : DSM 6.1.7-15284

config file (personal information replaced with xx):

```
{
  "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
  "bridge": {
    "name": "Homebridge",
    "username": "CK:xx:xx:BD:xx",
    "port": xxxxx,
    "pin": "xxx-xx-xxx"
  },
  "accessories": [
    {
      "accessory": "SynologyDiskstation",
      "name": "Home_Master",
      "host": "192.168.1.xx",
      "mac": "00:11:xx:xx:xx",
      "port": "5000",
      "secure": false,
      "account": "xxxxx",
      "password": "xxxxx",
      "version": 6.1,
      "doPolling": true,
      "pollingInterval": 60
    }
  ],
  "platforms": [
    {
      "platform": "HarmonyHub",
      "name": "Harmony Hub"
    }
  ]
}
```

**Comment by ultraflorescence** [comment]
Use the config posted above

**Comment by DutchmanNL** [comment]
i did :

```
    {
      "accessory": "Synology",
      "name": "Diskstation",
      "ip": "192.168.10.200",
      "mac": "00:11:xx:xx:xx:xx",
      "port": "5000",
      "secure": false,
      "account": "xxx",
      "password": "xxxx",
      "version": 6,
      "timeout": 5000,
      "disabled": [],
      "doPolling": true,
      "pollingInterval": 60
    }
```

**Comment by cbrandlehner** [comment]
Works for me with Diskstation DS1815+ and DSM DSM 6.2.1-23824 Update 6.
The Disk Usage seems to refer to the usage of Volume 1 (not the usage of the physical disk 1) - not sure about that. 
I disabled "switch" to prevent shutting down the Diskstation by accident in the Home App.

Good work!

**Comment by mauricelumiere** [comment]
Hello :)

Could anyone help me? I get this Error, but the Login is correct. 

> Can't login to Diskstation. Error Code: 402

Thank you!

**Comment by GusMuche** [comment]
Ok i've tested today and to have it work : 

1. Add a user to synology to the admin group
2. Disable http to https
3. Don't use secure mode on the plugin
4. Add the optional parameter for polling
5. Restart homebridge

And it's work. 

But : Home app only show T° and switch for power, to view CPU and Disk usage, I need to use the eve app (like the README say)

So it'll be interesting to have more return of the plugin to know were the errors are and also if possible add the CPU and Disk usage inside the home app...

Thanks for this job !

**Comment by ToBro14** [comment]
> But : Home app only show T° and switch for power, to view CPU and Disk usage, I need to use the eve app (like the README say)
> 
> So it'll be interesting to have more return of the plugin to know were the errors are and also if possible add the CPU and Disk usage inside the home app...

Same for me here. Works fine, but only shows CPU and disk usage in Eve and not in Home App
