### ISSUE TITLE
UPS status?

### ISSUE THREAD

**Issue by pashdown** [stfnhmplr/homebridge-synology#34]
Is it possible to extend this to cover UPS status?  I don't care about the other options, but knowing when there is a power outage in my home would be a useful notification.

**Comment by Erokani** [comment]
I'd appreciate as well :)

Thanks

**Comment by DanielWeeber** [comment]
See Package homebrige-nut

**Comment by stfnhmplr** [comment]
Since there is already a package, i'll close this.
