### ISSUE TITLE
Connection via HTTPS

### ISSUE THREAD

**Issue by Ghost108** [stfnhmplr/homebridge-synology#35]
Hello and thank you very much for this greatfull plugin.
Works good !

But please make it possible, to use it with enabled HTTPS and redirect from HTTP > HTTPS
Thanks a lot :)

**Comment by stfnhmplr** [comment]
Hello @Ghost108 
please try the latest release. It should fix the problems with the self-signed certificates. Tested with a DS211j.

**Comment by Ghost108** [comment]
Now it works with HTTPS.
Thanks ! :)
