### ISSUE TITLE
2FA Support?

### ISSUE THREAD

**Issue by apographon** [stfnhmplr/homebridge-synology#39]
Will 2FA come at some point in time?

**Comment by stfnhmplr** [comment]
Unfortunately, the 2FA from Synology is not documented. An otp_code is mentioned in the DownloadStation Api (https://global.download.synology.com/download/Document/DeveloperGuide/Synology_Download_Station_Web_API.pdf), but not described how to get it.

Therefore no implementation is possible until further notice.
