### ISSUE TITLE
DSM 7 Support

### ISSUE THREAD

**Issue by McDin** [stfnhmplr/homebridge-synology#49]
Hi,

with DSM 7 it is not possible to shutdown anymore. Will we get an update for DSM 7? :)

thanks

**Comment by PPPP114** [comment]
I have the same problem, would be nice to resolve it!

**Comment by stfnhmplr** [comment]
I currently do not have a device running DSM 7. So I cannot provide an update at the moment.

**Comment by McDin** [comment]
Okay. Can I help you with some needed data or test it for you?

**Comment by Mart-Muc** [comment]
same prob here on 220+
how can i help?

**Comment by stfnhmplr** [comment]
I just released a beta version with a complete rewritten codebase. The CPU usage and disk usage quote are not available anymore. Maybe they will come back with a later version.

You can install the beta version with `npm install -g homebridge-synology@beta`. There are several changes, so you have to update your `config.json`. For further information see https://github.com/stfnhmplr/homebridge-synology/tree/beta

Any feedback is welcome!

**Comment by bsoener** [comment]
pi@homebridge:/var/lib/homebridge $ npm install -g homebridge-synology@beta
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/assert-plus
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/asynckit
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/aws-sign2
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/aws4
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/caseless
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/core-util-is
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/dashdash
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/deep-equal
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/delayed-stream
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/combined-stream
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/extend
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/extsprintf
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/fast-deep-equal
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/fast-json-stable-stringify
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/forever-agent
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/getpass
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/har-schema
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/inherits
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/is-typedarray
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/isstream
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/jsbn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/json-schema
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/json-schema-traverse
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/json-stringify-safe
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/mime-db
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/mime-types
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/form-data
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/ms
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/debug
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/oauth-sign
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/pauseable
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/performance-now
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/polling-to-event
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/psl
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/punycode
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/qs
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/request/node_modules/extend
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/safe-buffer
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/safer-buffer
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/asn1
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/ecc-jsbn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/tough-cookie
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/tunnel-agent
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/tweetnacl
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/bcrypt-pbkdf
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/sshpk
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/uri-js
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/ajv
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/har-validator
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/util
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/uuid
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/verror
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/jsprim
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/http-signature
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/request
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/wake_on_lan
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/homebridge-synology/node_modules/request/node_modules
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/homebridge-synology/node_modules/assert-plus
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-synology/node_modules/assert-plus'
npm ERR!  [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/homebridge-synology/node_modules/assert-plus'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/homebridge-synology/node_modules/assert-plus'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-09-17T15_59_43_376Z-debug.log

**Comment by McDin** [comment]
@bsoener: I had to uninstall it first

**Comment by McDin** [comment]
> I just released a beta version with a complete rewritten codebase. The CPU usage and disk usage quote are not available anymore. Maybe they will come back with a later version.
> 
> You can install the beta version with `npm install -g homebridge-synology@beta`. There are several changes, so you have to update your `config.json`. For further information see https://github.com/stfnhmplr/homebridge-synology/tree/beta
> 
> Any feedback is welcome!

[17/09/2021, 18:07:48] [Synology] Initializing synology accessory...
[17/09/2021, 18:07:48] Error: Api version: 7.0.0 is not available. Available versions are: 5.0, 5.1, 5.2, 6.0, 6.0.1, 6.0.2, 6.0.3, 6.1, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.1.6, 6.1.7, 6.2, 6.2.1, 6.2.2, 6.2.3
    at new Syno (/usr/local/lib/node_modules/homebridge-synology/node_modules/syno/dist/syno.js:812:27)
    at new SynologyAccessory (/usr/local/lib/node_modules/homebridge-synology/src/SynologyAccessory.ts:58:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:350:50
    at Array.forEach (<anonymous>)
    at Server.loadAccessories (/usr/local/lib/node_modules/homebridge/src/server.ts:270:29)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:162:12)

Seems that DSM 7 is still not supported?

**Comment by bsoener** [comment]
by uninstalling the installation still does not work.

**Comment by McDin** [comment]
Tried with sudo?

**Comment by stfnhmplr** [comment]
@bsoener Depending on your environment you have to install the package with sudo: `sudo npm install -g homebridge-synology`.

> Seems that DSM 7 is still not supported?
That's what I can't test. But there was another bug, which I fixed with this new beta. The underlying package supports official only up to DSM 6.2.3, but I think it will work also with DSM 7. So even if you have DSM 7, please try to set the version in your `config.json` to `6.2.3.`

**Comment by bsoener** [comment]
Arggh forgot. but now i have this error message?

No plugin was found for the accessory "Synology" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by McDin** [comment]
> @bsoener Depending on your environment you have to install the package with sudo: `sudo npm install -g homebridge-synology`.
> 
> > Seems that DSM 7 is still not supported?
> > That's what I can't test. But there was another bug, which I fixed with this new beta. The underlying package supports official only up to DSM 6.2.3, but I think it will work also with DSM 7. So even if you have DSM 7, please try to set the version in your `config.json` to `6.2.3.`

It works. Thank you very much. Can I disable temperature? It shows 0 Degrees

**Comment by stfnhmplr** [comment]
@bsoener The "Synology" must be written in lower case.
```
{
            "accessory": "synology",
            "name": "Diskstation",
            "host": "192.168.1.1",
            "mac": "A1:B2:C3:D4:E5:F6",
            "port": 5000,
            "protocol": "http",
            "username": "your-username",
            "password": "your-password",
            "version": "6.2.2",
            "otp": "otp-code for 2FA",
            "startupTime": 60,
            "shutdownTime": 60,
            "disabled": [],
        }
```

@McDin Great News 😀  Yes, you can disable the temperature with a config entry. Simply add `disabled: ["temperature"]`. The right temperature should show up after 30 seconds. If it is then still at 0 degrees, something is wrong. Which Diskstation model do you have?

**Comment by bsoener** [comment]
ok it works Thanks

**Comment by McDin** [comment]
It is DS 218+ and is also not shown after 10 minutes. But for me it is no problem. I only want to start and shutdown the Synology in automations

**Comment by McDin** [comment]
But if you are interested in it this comes from the log:
[17/09/2021, 18:58:39] [Synology] Can't get temperature, Error: connect ECONNREFUSED 192.168.0.38:4000
[17/09/2021, 18:59:09] [Synology] Can't get temperature, Error: Unknown error
[17/09/2021, 18:59:39] [Synology] Can't get temperature, Error: Unknown error
[17/09/2021, 19:00:09] [Synology] Can't get temperature, Error: Unknown error

After that it repeats sometimes without first error.

**Comment by McDin** [comment]
> @bsoener The "Synology" must be written in lower case.
> 
> ```
> {
>             "accessory": "synology",
>             "name": "Diskstation",
>             "host": "192.168.1.1",
>             "mac": "A1:B2:C3:D4:E5:F6",
>             "port": 5000,
>             "protocol": "http",
>             "username": "your-username",
>             "password": "your-password",
>             "version": "6.2.2",
>             "otp": "otp-code for 2FA",
>             "startupTime": 60,
>             "shutdownTime": 60,
>             "disabled": [],
>         }
> ```
> 
> @McDin Great News 😀 Yes, you can disable the temperature with a config entry. Simply add `disabled: ["temperature"]`. The right temperature should show up after 30 seconds. If it is then still at 0 degrees, something is wrong. Which Diskstation model do you have?

Hi, I have still a problem. First time shutting down and starting works like a charm, but after it doesn't I always get the error above. Only way I found to fix it is to restart homebridge and then it works again for one shutdown and one start. I'm not sure what the problem is. Yesterday when I go sleeping it should shutdown the second time after the first test and it was still online this morning. So I tried it some time and it was always the same behavior.

[18/09/2021, 09:30:12] [Synology] Shutting down Synology
[18/09/2021, 09:30:12] [Synology] Can't shutdown Synology: Error: Unknown error

Do you have an clue for this? I'm already in debug mode through GUI but I don't get more infos.

**Comment by PPPP114** [comment]
Hello,

I tried in my 718+ with DSM7 and is working fine (including the temperature)!

Thank you very much!

PP

**Comment by stfnhmplr** [comment]
> Do you have an clue for this? I'm already in debug mode through GUI but I don't get more infos.

I don't have any clue what's wrong there. This seems to be the same issue, why the temperature does not show up. The error messages show some connection issues, but this could have several reasons. Quite hard to debug, if the nas just reports an unknown error 🤔 I will take a look if there is any chance to get a better error message.

**Comment by stfnhmplr** [comment]
> Hi, I have still a problem. First time shutting down and starting works like a charm, but after it doesn't I always get the error above. Only way I found to fix it is to restart homebridge and then it works again for one shutdown and one start.

@McDin Through #53 I found the reason for this. Should be fixed with `0.4.2`.

**Comment by v2px** [comment]
Digging this up again because since this change for DSM 7 was implemented, I have a hard time shutting down my DSM 6.2 NAS with the same error ([Diskstation] Can't shutdown Diskstation: Error: Unknown error).
I have not changed credentials and with previous versions it worked flawlessly.

**Comment by stfnhmplr** [comment]
@v2px Have you updated your configuration? There are some changes to make. You can find an example in the ReadMe.

**Comment by v2px** [comment]
> @v2px Have you updated your configuration? There are some changes to make. You can find an example in the ReadMe.

Yes, my configuration looks sane! Every other feature works as well. I think it might be the change you did for DSM 7.

**Comment by stfnhmplr** [comment]
Please open a new issue and provide the required information. I need the log output and your configuration part for this plugin.
