### ISSUE TITLE
Can't get temperature, can't set switch, can't see Disk Usage    (Logfile: "Error: HTTP status code: 400")

### ISSUE THREAD

**Issue by ToniKater** [stfnhmplr/homebridge-synology#53]
**Describe The Bug:**
After installing version 0.4.0 i can't get temperature and can't switch the diskstation off. Seeing an error in the logs: "Error: HTTP status code: 400". And additional: The Disk Usage isn't shown. 

I've tried "protocol: http" and "protocol: https".
I've tried "version: 6.2.2" and "version: 6.2.4" too. 
I've used the workaround "accessory": "synology". 

Switch "on" and display of state works very well with "protocol: https" and "version: 6.2.4"!

The Synology Diskstation type: DS214+ (DSM 6.2.4-25556 Update 2)  

**To Reproduce:**

**Expected behavior:**
can see the temperature and switch the diskstation on/off

**Logs:**

```
[13/10/2021, 14:56:18] [DISKSTATION] Initializing synology accessory...
[13/10/2021, 14:56:26] [Homebridge UI] Homebridge Config UI X v4.41.2 is listening on :: port 8080
[13/10/2021, 14:56:27] [DISKSTATION] Synology DISKSTATION finished initializing!
...
[13/10/2021, 15:04:27] [DISKSTATION] Can't get temperature, Error: HTTP status code: 400
[13/10/2021, 15:05:06] [DISKSTATION] Can't shutdown DISKSTATION: Error: HTTP status code: 400
```

**Plugin Config:**

```json
        {
            "name": "DISKSTATION",
            "host": "192.168.XX.YY",
            "mac": "00:11:22:33:44:55",
            "port": 5001,
            "username": "masterofdesaster",
            "password": "topsecret",
            "protocol": "https",
            "version": "6.2.4",
            "startupTime": 60,
            "shutdownTime": 60,
            "disabled": [],
            "accessory": "synology"
        }
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 0.4.0
* **Homebridge Version**: 1.3.5
* **Node.js Version**: 14.18.1
* **NPM Version**: 6.14.15
* **Operating System**: Raspbian GNU/Linux Stretch (9)

**Comment by stfnhmplr** [comment]
@ToniKater Thanks for the coffee. Always welcome 😊
I could reproduce this behavior and just released a fix. `0.4.2` should solve this issue.

**Comment by Tontonpat** [comment]
Thanks, is it possible to display the temperature of the disks in addition to that of the cpu?
