### ISSUE TITLE
Compatibility with latest homebridge release

### ISSUE THREAD

**Issue by mbierman** [stfnhmplr/homebridge-synology#54]
**Describe The Bug:**
Plug-in no longer compatible with homebridge. 

**To Reproduce:**
1. Install latest homebridge.
2. See error in screenshot below.

**Expected behavior:**
Plug-in is compatible with current homebridge.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json

{
    "accessory": "Synology",
    "name": "",
    "ip": "192.168.0.19",
    "mac": ":43",
    "port": "5001",
    "secure": true,
    "account": "",
    "password": "",
    "version": 6,
    "timeout": 15000,
    "disabled": [
        "temp"
    ]
}

```

**Screenshots:**
![3033948E-9EFF-4235-A01F-1130E7868E63](https://user-images.githubusercontent.com/1205471/137176637-b7b085c7-9302-487b-890c-c147ef2ee4ab.png)

**Environment:**

* **Node.js Version**: 14.18.1
* **NPM Version**: 6.14.15
* **Homebridge Version**: 1.3.5
* **Homebridge Config UI X Version**: v4.41.2
* **Operating System**: Docker
* **Process Supervisor**: Docker 
* **Alpine Linux**: 3.12.8

**Comment by Tontonpat** [comment]
Hi, that's the same for me.

**Comment by stfnhmplr** [comment]
> See error in screenshot below.

I can't see that you have version 0.4.0 installed. The screenshot below shows just version 0.3.1.
Also, I can't see any error message in the screenshot.

> `"accessory": "Synology",`

The Synology must be lowercase --> `synology`

**Comment by mbierman** [comment]
Thanks! the capitalization never seemed to matter before. The errors are: 
```
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[       ...........] - extract:homebridge-synology: verb lock using /root/.npm/_locks/
```

But now it is at least installing.

**Comment by nobiman** [comment]
OK, it initializes, but does not show state or temperature, like v 3.1 does. Downgraded to 3.1.
