### ISSUE TITLE
If Switch is disabled it is no longer displayed in Homekit or Eve App

### ISSUE THREAD

**Issue by JayJay-Master** [stfnhmplr/homebridge-synology#56]
I run homebridge in a docker container on a Synology NAS. Therfore it is essential, to disable the possibility switch off the Synology.
If Switch is disabled it is no longer displayed in Homekit or Eve app, and therefore it is no longer possible to see cpu and disk usage in Eve app. In older version of the plugin Synology switch was visible, but it was not possible to switch off the nas.

Include 
            "disabled": [
                "switch"
            ],
in configuration

Synology switch should be visible, but it should not be possible to switch off the nas.

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
        {
            "name": "DS416play",
            "host": "192.168.178.xy",
            "mac": "00:11:32:11:22:33",
            "port": 5001,
            "username": "_username_",
            "password": "_password_",
            "protocol": "https",
            "version": "6.2.2",
            "startupTime": 60,
            "shutdownTime": 60,
            "disabled": [
                "switch"
            ],
            "accessory": "synology"
        }
 ```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-synology v0.4.2 
* **Homebridge Version**: Homebridge v1.3.5 (oznu/homebridge:latest)
* **Node.js Version**: v14.18.1
* **NPM Version**: v6.14.15 
* **Operating System**: Synology DSM 6.2.4 / Docker / Alpine Linux (3.12.8)

**Comment by stfnhmplr** [comment]
I just tried to recreate this. In both the Home app and the Eve app, the sensors are displayed even when the switch is deactivated. Since a switch without function is not necessarily a good solution, I actually do not want to use the old variant anymore.

![IMG_3276](https://user-images.githubusercontent.com/3863403/144300102-a53137d7-c0bf-46c8-9acb-08417d734f77.jpeg)
