### ISSUE TITLE
Temperature readout

### ISSUE THREAD

**Issue by adamengineering** [stfnhmplr/homebridge-synology#59]
The Plugin reports the following error:

Can't get temperature, Error: write EPROTO 3070040768:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

Installed the plug-in under Homebridge V1.3.8, Synology DS920+ running DSM 7.0.1-42218
Switch for Startup and Shutdown works - disabled the Temperature readout in the config file, for the moment, as Homebridge kept reporting error messages.

{
    "name": "Diskstation",
    "host": "192.168.X.X",
    "mac": "AA:BB:CC:DD:EE:FF",
    "port": 5000,
    "username": "username",
    "password": "password",
    "protocol": "https",
    "version": "6.2.2",
    "startupTime": 60,
    "shutdownTime": 60,
    "accessory": "synology",
    "disabled": [
        "temperature"
    ]
}

Plugin Version: 0.4.2
Homebridge Version: 1.3.8
Node.js Version: 16.13.0
NPM Version: 8.1.3
Operating System: Raspbian

**Comment by stfnhmplr** [comment]
This error is related to your configuration. Make sure, that the `protocol` matches the specified port. With a default configuration, the port should be 5001 when using `https` and 5000 when using `http`.

**Comment by adamengineering** [comment]
What a difference a 1 from a 0 makes ;-) Thanks for pointing that out. Now the error is gone, unfortunately the Temperature readout is always 0°. Anything else that i need to setup?

**Comment by stfnhmplr** [comment]
Yes, those tiny little details... 😅

Glad to see it working now. Regarding the temperature: The most common issue is that the user you're using does not have admin rights. If this is not the case please activate the debug mode and post the log here. There should be more information.

**Comment by adamengineering** [comment]
The User has all admin rights possible on the Synology. Homebridge reports the following error message: `Can't get temperature, Error: No such account or incorrect password`

Where do I activate the debug mode?

**Comment by stfnhmplr** [comment]
The debug mode is obviously not needed here. You already have the error message. Wrong username or password. If you've enabled 2FA, have a look at the information in the Readme.

**Comment by adamengineering** [comment]
Sorry, I don't have 2FA enabled - so the ReadMe does not help me much with my error.

`[Diskstation] Can't get temperature, Error: No such account or incorrect password`

I'm 100% sure that my username and password is entered correctly. I even created a new user to test it with no success. The pliugin insists on the error message. If I disable the temperature readout, the plugin reports back when the device is online, starts up or shuts down. Some form of communication seems to be working... Still haven't found the debug mode, maybe in there I could find further information.

**Comment by stfnhmplr** [comment]
> Still haven't found the debug mode

Instructions for enabling the debug mode can be found here: https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting

> I'm 100% sure that my username and password is entered correctly. I even created a new user to test it with no success

Did you restart homebridge after you changed your `config.json`? The error message is directly returned from your diskstation. Can you shutdown your diskstation using the switch in Homekit?

**Comment by adamengineering** [comment]
Yes, I did restart the Homebridge every time I change something in the config. Yes I'm able to shutdown using the switch.

So this are the only two messages appearing in the Debug Mode:
`[10/12/2021, 08:49:29] [Diskstation] Initializing synology accessory...
[10/12/2021, 08:49:29] [Diskstation] Synology Diskstation finished initializing!`

No additional error message, still the temperature readout in the plugin says 0° (instead of 43° as reported by the DSM)

**Comment by stfnhmplr** [comment]
If you're able to shut down the diskstation with the switch, I don't understand what's going on there. Both commands, for shutting down and querying the temperature, use the same connection and credentials. So the error message from the diskstation makes no sense to me. I've tried several things (new user, different permissions and so on) but I can not reproduce this behavior.

**Comment by adamengineering** [comment]
Thanks für the update!

My Device is a DS920+ with DSM 7.0.1-42218 installed on it, maybe the Problem lies within the new DSM? All 4 Bay's are filled with HDD and the SSD Cache is installed. Could it be that I use the LAN in a Bond? I don't know what else I can tell you...

**Comment by stfnhmplr** [comment]
@adamengineering There was a similar error in the issue linked above. Can you please check if the IP address of the Homebridge host is blocked or auto-block is enabled?

Instructions: https://kb.synology.com/en-global/SRM/help/SRM/NetworkCenter/security_autoblock?version=

**Comment by adamengineering** [comment]
Sorry, for the late reply... Yes, indeed the auto-block prevented my Homebridge to get access to my NAS. I've added it to the white-list and it seems it's no longer getting blocked. I can see the Temp Gauges in Homebridge, only that the readout is always 0° - does never change, for both gauges Temp and Average Disk.

**Comment by adamengineering** [comment]
Today, i picked up a new SD-Card and did a complete fresh Installation with the latest Homebridge Installer available, updated all packages and NPM. Installed the plugin and with this new SD-Card it's working as intended. I see the status of the NAS, both Temperatures are read, no complains anymore about the account or the password.

I can't say what the difference is, as the installation on the other SD-Card was updated regularly and has theoretically the same version running... Anyway I'm happy that it is working. Thank you for your patience in supporting me, much appreciated!
