### ISSUE TITLE
shutdown doesnt work

### ISSUE THREAD

**Issue by fildy** [stfnhmplr/homebridge-synology#6]
hi,

I'm using DS412+ and shutdown is not working.
any workaroud I can do?

**Comment by stfnhmplr** [comment]
Which DSM Version do you use? this plugin does not work with DSM 6.
If you are using DSM 5: Is there any error message?

**Comment by fildy** [comment]
I see, I'm using DSM 6

**Comment by dakikifr** [comment]
Will the plugin be updated for DSM6 someday, or is it abandoned?
I tried to fix it, but couldn't find any documentation for the APIs you are using (besides login, which works fine).

**Comment by sho3it** [comment]
please update for DSM6

**Comment by stfnhmplr** [comment]
update for DSM6 is in progress. perhaps it's done next weekend.

**Comment by dakikifr** [comment]
Good to know, just a question though.
Where did you find the documentation for the new APIs?

**Comment by stfnhmplr** [comment]
**New version with support for DSM 6 is available.**

I have not found any documentation related to DSM 6. But you can watch the queries at the web interface to get the informations.
