### ISSUE TITLE
Warning during Update

### ISSUE THREAD

**Issue by CHTHSCH** [stfnhmplr/homebridge-synology#62]
**Describe The Bug:**
Warning messages during update to V.0.5.0

**To Reproduce:**
Update the add-on

**Expected behavior:**
No warning or error messages

**Logs:**
```
USER: pi
DIR: /usr/local
CMD: sudo -E -n npm install -g homebridge-synology@latest

npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
⸨##################⸩ ⠇ reify:lodash: timing reifyNode:node_modules/homebridge-synology
```

**Plugin Config:**
n/a

**Screenshots:**
n/a

**Environment:**

* **Plugin Version**: 0.5.0
* **Homebridge Version**: 1.3.8
* **Node.js Version**: v16.13.1
* **NPM Version**: 8.1.2
* **Operating System**: Raspbian GNU/Linux Buster (10)

**Comment by stfnhmplr** [comment]
These warnings are not in the scope of this package as they are all related to `request.js`, a sub dependency of homeinstalator/syno.
