### ISSUE TITLE
Nas turns on but does not turn off

### ISSUE THREAD

**Issue by fatez** [stfnhmplr/homebridge-synology#63]
My synology (DS1019+) is correctly configured to be turned on from WOL and in fact I can do it without any problem but I can't turn it off from the HomeBridge icon: the icon turns off but the nas remains on.

thanks

**Comment by stfnhmplr** [comment]
WOL sends a magic packet to your Diskstation. The shutdown, on the other hand, is solved via the API, where your credentials and connection parameters are needed. So please check your configuration first. If the problem still exists, please post your log here.

**Comment by fatez** [comment]
Thanks for reply, i double checked and login/password are correct.
This is my config : I have hidden some information with the "xx" but as I said before they are correct

```
{
            "accessory": "synology",
            "name": "DS1019",
            "host": "192.168.xx.xxx",
            "mac": "00:11:xx:xx:xx:xx",
            "port": 5000,
            "protocol": "http",
            "username": "xxx",
            "password": "xxx",
            "version": "6.2.2",
            "otp": {
                "title": "OTP-Code",
                "type": "string",
                "required": false
            },
            "startupTime": 10,
            "shutdownTime": 10,
            "disabled": [
                "temperature"
            ]
        },
```

The log says :

`[20/12/2021, 21:46:05] [DS1019] Can't shutdown DS1019: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object`

**Comment by stfnhmplr** [comment]
> Can I leave it like this, without the section ?

Sure. The otp configuration is only needed if you have enabled 2FA. And you don't need to disable anything. This is only needed if you want to disable some features of this plugin. You'll find more information in the ReadMe.
