### ISSUE TITLE
DSM 7.0.1

### ISSUE THREAD

**Issue by drbelt27** [stfnhmplr/homebridge-synology#67]
After upgrading ti DSM 7.0.1 the plugin stop Wirkung :(

It‘s possibile ti extend the compatibilità vor Thais plugin at DSM 7 ?

**Comment by drbelt27** [comment]
![Uploading 365662CE-9446-4EB5-AA93-9A7ECBAB0BDE.jpeg…]()

**Comment by drbelt27** [comment]
![F56AE351-55BE-4145-8222-849774A7EFD5](https://user-images.githubusercontent.com/64604481/148105270-b7e58cdf-541b-41d5-8511-7457d54ec5dd.jpeg)

**Comment by stfnhmplr** [comment]
It should work with DSM 7. Please post your config (without credentials) here and I need to know some information about your environment:

Plugin Version:
Homebridge Version:
Node.js Version:
NPM Version:
Operating System:

**Comment by drbelt27** [comment]
Version Node.js: v16.13.1
NPM Version: v8.1.2
Homebridge Version: 1.3.9
Synology Plugin: 0.5.0
Ubuntu 20.04 lts

**Comment by drbelt27** [comment]
I have changed the system 
Raspbian GNU/Linux Bullseye (11)

**Comment by stfnhmplr** [comment]
> Please post your config (without credentials) here

Again: Please post your configuration for this plugin (from your `config.json`).

**Comment by drbelt27** [comment]
"name": "Diskstation",
            "host": "192.168.172.10",
            "mac": "00-11-32-88-A9-99",
            "port": 5000,
            "username": "matteo",
            "password": "**********",
            "protocol": "https",
            "version": "6.2.2",
            "startupTime": 60,
            "shutdownTime": 60,
            "otp": "*******",
            "accessory": "synology"

**Comment by stfnhmplr** [comment]
Your config is wrong. Make sure, that the protocol matches the specified port. With a default configuration, the port should be 5001 when using `https` and 5000 when using `http`.

**Comment by drbelt27** [comment]
Sorry 

I’m not see the port miss configuration :(
Now work perfectly 

Thank you!!
