### ISSUE TITLE
WOL not same network

### ISSUE THREAD

**Issue by Musyanon** [stfnhmplr/homebridge-synology#68]
Hello,

I have install this plugin, I can see temp and shutdown the NAS, but I can't startup it.
My NAS is not in my home, I use external IP and MAC address to startup. I think your plugin use only MAC address, it's possible to use also the IP ?

Many thanks !

**Comment by stfnhmplr** [comment]
Since WOL, as far as I know, only works with a MAC address, this is unfortunately not possible. WOL is a broadcast protocol that operates at a level below IP addresses.
