### ISSUE TITLE
temperature doesn't work on diskstation 6

### ISSUE THREAD

**Issue by andig** [stfnhmplr/homebridge-synology#7]
Always shows 0. Might this be helpful: https://github.com/yannickcr/node-synology/wiki/synology-dsm ?

**Comment by stfnhmplr** [comment]
Which NAS do you have? Are the other values displayed correctly?
I know the repository, but it is only a wrapper for the dsm api call.

**Comment by andig** [comment]
Argh! My mistake- invalid login. Maybe add an error message when the login fails? Didn't catch this as power state was shown correctly...
