### ISSUE TITLE
No update Data

### ISSUE THREAD

**Issue by Vaifranz** [stfnhmplr/homebridge-synology#71]
Thanks for your work, I am using this plug-in to monitor my Synology NAS, have recently upgraded to DSM 7.0.1 (previously DSM 6.2.4 and everything worked OK with Docker) and am using oznu package (Intel v2.2.1) without using Docker, I am having problems with not updating

```
[2/15/2022, 2:45:33 PM] [NET Reserve] Device is not online; Polling temperature disabled.
[2/15/2022, 2:45:33 PM] [NET Reserve] Device is not online; Polling disk temperature disabled.
```

The settings are correct because it worked before DSM 7.0.1, here my configuration

     
 ```
  {
            "name": "NET Reserve",
            "host": "192.168.***.***",
            "mac": "**:**:**:**:**:**",
            "port": 5501,
            "username": "*******",
            "password": "**********",
            "protocol": "https",
            "version": "6.2.2",
            "startupTime": 60,
            "shutdownTime": 60,
            "accessory": "synology"
        },
```

What am I doing wrong or forgetting ? Same issue with "http". Thanks in advance.

**Comment by stfnhmplr** [comment]
Your welcome. The error message says that the device cannot be reached. The reachability is determined with ping. Could you please check if your Synology NAS is pingable from your Homebridge host? If your device cannot be pinged, the temperature query will be disabled and the error message shown above will appear.

**Comment by Vaifranz** [comment]
> Can I ask if you use 2FA? I cannot get 2FA to work after upgrading to DSM 7.

I am not using 2FA

**Comment by bjornand1** [comment]
@Vaifranz Because I see so many attempts at intrusion into the Synology.

**Comment by Vaifranz** [comment]
Ping works, even with other devices I have the same problem, they don't update. Now I can't even reinstall the plug-in (I uninstalled it because it didn't work).

**Comment by Vaifranz** [comment]
> @Vaifranz Because I see so many attempts at intrusion into the Synology.
 Passwordless Sign-in only.

**Comment by bjornand1** [comment]
So I finally got this to work with 2FA, but in HomeKit, the Synology is shown as off and temperatures at 0 degrees.

**Comment by bjornand1** [comment]
Additional update: I uninstalled the plugin, enabled SSH and installed it again using sudo rights. But I still see the same issue; the disk station shows as off even when it is on, and the temperatures show as zero degrees. What can I be doing wrong here?

**Comment by stfnhmplr** [comment]
> Ping works, even with other devices I have the same problem, they don't update.
Can't follow here. Which other devices?

> Now I can't even reinstall the plug-in (I uninstalled it because it didn't work).
Can't help here without any error messages/log output.

**Comment by bjornand1** [comment]
Hi, it has been a while since I bothered with this, so I was wondering if any new tips have surfaced? The plugin is installed and the config entry is, as far as I can tell, correct. Still, the disk station is shown as off, even when being on, and the temperature readings are zero degrees. Any ideas about why this does not work?

**Comment by mames13** [comment]
Any updates on this problem?
