### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by ariakeumi** [stfnhmplr/homebridge-synology#72]
USER: root
DIR: /homebridge
CMD: npm install --save homebridge-synology@latest

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
npm ERR! ssh -oStrictHostKeyChecking=accept-new: line 1: ssh: not found
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-03-06T06_28_38_246Z-debug-0.log

Command failed. Please review log for details.

/homebridge # cat /root/.npm/_logs/2022-03-06T06_37_49_760Z-debug-0.log
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/bin/npm',
0 verbose cli   'install',
0 verbose cli   '--save',
0 verbose cli   'homebridge-synology@latest'
0 verbose cli ]
1 info using npm@8.3.1
2 info using node@v16.14.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 19ms
6 timing config:load:builtin Completed in 57ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/homebridge/.npmrc Completed in 0ms
10 timing config:load:project Completed in 18ms
11 timing config:load:file:/root/.npmrc Completed in 4ms
12 timing config:load:user Completed in 6ms
13 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 19ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 112ms
19 timing npm:load:configload Completed in 112ms
20 timing npm:load:setTitle Completed in 3ms
21 timing config:load:flatten Completed in 13ms
22 timing npm:load:display Completed in 18ms
23 verbose logfile /root/.npm/_logs/2022-03-06T06_37_49_760Z-debug-0.log
24 timing npm:load:logFile Completed in 7ms
25 timing npm:load:timers Completed in 1ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 143ms
28 timing arborist:ctor Completed in 1ms
29 silly logfile start cleaning logs, removing 1 files
30 timing idealTree:init Completed in 319ms
31 timing arborist:ctor Completed in 0ms
32 http fetch GET 200 https://registry.npmjs.org/homebridge-synology 1503ms (cache revalidated)
33 timing idealTree:userRequests Completed in 1509ms
34 silly idealTree buildDeps
35 silly fetch manifest homebridge-synology@0.5.0
36 silly placeDep ROOT homebridge-synology@0.5.0 OK for:  want: 0.5.0
37 silly fetch manifest @types/ping@^0.2.0
38 silly fetch manifest @types/wol@^1.0.0
39 silly fetch manifest axios@^0.21.1
40 silly fetch manifest ping@^0.4.0
41 silly fetch manifest syno@git+https://github.com/homeinstalator/syno.git
42 silly fetch manifest wol@^1.0.7
43 http fetch GET 200 https://registry.npmjs.org/@types%2fping 518ms (cache revalidated)
44 http fetch GET 200 https://registry.npmjs.org/wol 1296ms (cache revalidated)
45 http fetch GET 200 https://registry.npmjs.org/axios 1328ms (cache revalidated)
46 http fetch GET 200 https://registry.npmjs.org/ping 1335ms (cache revalidated)
47 http fetch GET 200 https://registry.npmjs.org/@types%2fwol 1597ms (cache revalidated)
48 timing idealTree:#root Completed in 1608ms
49 silly placeDep node_modules/homebridge-synology @types/ping@0.2.1 OK for: homebridge-synology@0.5.0 want: ^0.2.0
50 silly placeDep node_modules/homebridge-synology @types/wol@1.0.1 OK for: homebridge-synology@0.5.0 want: ^1.0.0
51 silly placeDep node_modules/homebridge-synology axios@0.21.4 OK for: homebridge-synology@0.5.0 want: ^0.21.1
52 silly placeDep node_modules/homebridge-synology ping@0.4.1 OK for: homebridge-synology@0.5.0 want: ^0.4.0
53 silly placeDep node_modules/homebridge-synology syno@ OK for: homebridge-synology@0.5.0 want: git+https://github.com/homeinstalator/syno.git
54 silly placeDep node_modules/homebridge-synology wol@1.0.7 OK for: homebridge-synology@0.5.0 want: ^1.0.7
55 silly fetch manifest @types/node@*
56 silly fetch manifest follow-redirects@^1.14.0
57 silly fetch manifest q@1.x
58 silly fetch manifest underscore@^1.12.0
59 http fetch GET 200 https://registry.npmjs.org/underscore 229ms (cache revalidated)
60 http fetch GET 200 https://registry.npmjs.org/@types%2fnode 243ms (cache revalidated)
61 http fetch GET 200 https://registry.npmjs.org/q 270ms (cache revalidated)
62 http fetch GET 200 https://registry.npmjs.org/follow-redirects 276ms (cache revalidated)
63 timing idealTree:node_modules/homebridge-synology Completed in 297ms
64 timing idealTree:node_modules/homebridge-synology/node_modules/@types/ping Completed in 0ms
65 silly placeDep node_modules/homebridge-synology @types/node@17.0.21 OK for: @types/wol@1.0.1 want: *
66 timing idealTree:node_modules/homebridge-synology/node_modules/@types/wol Completed in 2ms
67 timing idealTree:node_modules/homebridge-synology/node_modules/@types/node Completed in 0ms
68 silly placeDep node_modules/homebridge-synology follow-redirects@1.14.9 OK for: axios@0.21.4 want: ^1.14.0
69 timing idealTree:node_modules/homebridge-synology/node_modules/axios Completed in 3ms
70 timing idealTree:node_modules/homebridge-synology/node_modules/follow-redirects Completed in 0ms
71 silly placeDep node_modules/homebridge-synology q@1.5.1 OK for: ping@0.4.1 want: 1.x
72 silly placeDep node_modules/homebridge-synology underscore@1.13.2 OK for: ping@0.4.1 want: ^1.12.0
73 timing idealTree:node_modules/homebridge-synology/node_modules/ping Completed in 3ms
74 timing idealTree:node_modules/homebridge-synology/node_modules/q Completed in 0ms
75 timing idealTree:node_modules/homebridge-synology/node_modules/syno Completed in 0ms
76 timing idealTree:node_modules/homebridge-synology/node_modules/underscore Completed in 0ms
77 timing idealTree:node_modules/homebridge-synology/node_modules/wol Completed in 0ms
78 timing idealTree:buildDeps Completed in 1917ms
79 timing idealTree:fixDepFlags Completed in 29ms
80 timing idealTree Completed in 3778ms
81 timing command:install Completed in 3799ms
82 verbose stack Error: An unknown git error occurred
82 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
82 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:36:26
82 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
83 verbose cwd /homebridge
84 verbose Linux 4.4.180+
85 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "homebridge-synology@latest"
86 verbose node v16.14.0
87 verbose npm  v8.3.1
88 error code 128
89 error An unknown git error occurred
90 error command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
91 error ssh -oStrictHostKeyChecking=accept-new: line 1: ssh: not found
91 error fatal: Could not read from remote repository.
91 error
91 error Please make sure you have the correct access rights
91 error and the repository exists.
92 verbose exit 128
93 timing npm Completed in 4345ms
94 verbose unfinished npm timer reify 1646548670301
95 verbose unfinished npm timer reify:loadTrees 1646548670318
96 verbose code 128
97 error A complete log of this run can be found in:
97 error     /root/.npm/_logs/2022-03-06T06_37_49_760Z-debug-0.log

**Comment by Alexeus1971** [comment]
Same problem with my new Homebridge installation.
Already have another Homebridge instance where this plugin is installed, but cannot make a new install.

**Comment by stfnhmplr** [comment]
Please read https://github.com/stfnhmplr/homebridge-synology/issues/58

If this does not apply, please provide some additional informations:

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by ariakeumi** [comment]
> 

homebridge-synology v0.5.0
homebridge v1.4.0
Node.js v16.14.0
Npm v8.3.1
Alpine Linux (3.12.9) oznu-homebridge

**Comment by ariakeumi** [comment]
> Please read #58
> 
> If this does not apply, please provide some additional informations:
> 
> * **Plugin Version**:
> * **Homebridge Version**:
> * **Node.js Version**:
> * **NPM Version**:
> * **Operating System**:

homebridge-synology v0.5.0
homebridge v1.4.0
Node.js v16.14.0
Npm v8.3.1
Alpine Linux (3.12.9) oznu-homebridge

**Comment by ariakeumi** [comment]
> 请阅读#58
> 
> 如果这不适用，请提供一些附加信息：
> 
> * **插件版本**：
> * **家桥版本**：
> * **Node.js 版本**：
> * **NPM 版本**：
> * **操作系统**：

okay,well,is syno dependency problem,thank you.
