### ISSUE TITLE
Start via homebridge is possible, but temp is constantly 0,0 and shut down is not doing what it did before

### ISSUE THREAD

**Issue by Jens2022** [stfnhmplr/homebridge-synology#73]
Dear Stefan, 

I really appreciate your work and the effort you put in that homebridge enhancement. It's a great help. 

I assume due to a recent Hoobs Homebridge update unfortunately it is behaving different then before. I can start the NAS via home kit / hoobs homebridge but I can't see the temp any longer. Unfortunately switching off doesn't work any longer. 

Could you help me wiht a hint how I potentially could fix this? 

Thanks a lot for your help and your support. 

Best regards

Jens
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by stfnhmplr** [comment]
Hi Jens. To be able to help you, I need more information. Please post the log output and your configuration.

**Comment by Jens2022** [comment]
Hi Stefan, 

sorry for the long delay. In the meantime I need to reset the hoobs in total. Your plugin (great help) allows my to switch my NAS on. But I can't switch of nore see the temperature. 

Please see log below. Thank you so much for a hint. 

Best regards

Jens

2.10.2022, 16:05:35SynologyLoaded plugin 'homebridge-synology'
2.10.2022, 16:05:38SynologyBridge is running on port 51856.
2.10.2022, 17:19:12SynologyConfiguration change
2.10.2022, 17:19:23SynologyLoaded plugin 'homebridge-synology'
2.10.2022, 17:19:23SynologyLoading 1 accessories...
2.10.2022, 17:19:23SynologyServerSynology Server finished initializing!
2.10.2022, 17:19:24SynologyBridge is running on port 51856.
2.10.2022, 17:19:28SynologyServerstate changed to Online; updated characteristic
2.10.2022, 17:20:04SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:20:04SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:20:29SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:20:33SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:20:59SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:21:04SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:21:30SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:21:35SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:21:59SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:22:04SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:22:29SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:22:32SynologyServerShutting down Server
2.10.2022, 17:22:34SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:22:36SynologyFEHLER[Synology 9B24@On] The write handler for the characteristic 'On' on the accessory 'Server' was slow to respond!
2.10.2022, 17:22:37SynologyServerFEHLERCan't shutdown Server: Error: No such account or incorrect password
2.10.2022, 17:23:00SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:23:04SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:23:30SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:23:34SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:23:59SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:24:05SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:24:29SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:24:32SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:24:59SynologyServerWARNUNGCan't get temperature, Error: No such account or incorrect password
2.10.2022, 17:25:04SynologyServerWARNUNGCan't get average disk temperature, Error: No such account or incorrect password
2.10.2022, 17:25:29SynologyServerWARNUNGCan't get average disk temperature, Error: Unknown error
2.10.2022, 17:25:29SynologyServerWARNUNGCan't get temperature, Error: socket hang up
2.10.2022, 17:25:53SynologyServerWARNUNGCan't get temperature, Error: connect ECONNREFUSED 192.168.178.10:5000
2.10.2022, 17:26:00SynologyServerstate changed to Offline; updated characteristic
2.10.2022, 17:26:17SynologyServerWARNUNGCan't get average disk temperature, Error: connect EHOSTUNREACH 192.168.178.10:5000
2.10.2022, 17:27:23SynologyServerServer woke up!
2.10.2022, 17:28:23SynologyServerFEHLERStartup time of 60s expired, reverting state to offline
2.10.2022, 17:28:24SynologyServerstate changed to Online; updated characteristic
2.10.2022, 17:28:29SynologyServerWARNUNGCan't get average disk temperature, Error: Unknown error

**Comment by Jens2022** [comment]
Ah .. found part of the problem ... I used the wrong user accout. So switching on an off works perfectly fine now. One the temperature is not displayed. 
Thanks for your help. 
Best Regards
Jens

**Comment by Jens2022** [comment]
Update ... works perfectly fine. Thanks a lot. Sorry for the lack of patience. 
Best regards
Jens

**Comment by Gummibando** [comment]
@Jens2022 Could you please elaborate about what you did to get the plugin working (again). It stopped working for me quite a while ago, same issues as with many of the other reports (device offline, temp shown as 0°). Your post is the first report of getting it working again. Thanks in advance.

**Comment by Jens2022** [comment]
@Gummibando: Hi, Oli. I needed to flash my hoobs and rebuild from scratch. This kind of a clean install did part of the job I guess. One the other side I found hints in my research that it might make a difference which account on the synology you adress. In my case I deleted the default admin account on the NAS, made my personal account to an admin account and used my credential for log in into the NAS as credentials in the set up of the plug in. First only switching on and off worked, after another restart also the temperature was displayed. I assume that this in not significantly helpful but maybe at least a bit. Best Regards, Jens

**Comment by Gummibando** [comment]
@Jens2022 Hi Jens. Thanks for the info. While my setup differs from yours (Oznu's "native" Synology package), I might follow the same route and start from scratch, as I can not – for the life of it – get it working, no matter what combination of settings, credentials etc. I try.
How do you get the debug info for the plugin? I don't see the plugin warnings or errors as shown in your readout.
Best, Oli

**Comment by stfnhmplr** [comment]
Since the original issue has been resolved, I'll close this.
