### ISSUE TITLE
Plugin wasn't found on loading 

### ISSUE THREAD

**Issue by astradti** [stfnhmplr/homebridge-synology#76]
Hi, 
i'm having issues with my homebridge-synology plugin

this is on restarting the homebridge
![image](https://user-images.githubusercontent.com/108151652/175651048-410c5a91-a5f1-4ec0-a3bd-6c628b2703f9.png)

![image](https://user-images.githubusercontent.com/108151652/175651137-34c12f2d-5423-4833-9bc3-105f844aba10.png)

this is the config in the json file. i covered some things for obvious reason

![image](https://user-images.githubusercontent.com/108151652/175651902-7e7d2419-94dd-44d8-b7e7-b3551b369fb5.png)

if i try to reinstall the plugin, i get this error:

![image](https://user-images.githubusercontent.com/108151652/175653932-3e6c8480-d4a4-40fc-9eeb-52d2b501d455.png)

can someone help me on what's wrong?

**Comment by JayJay-Master** [comment]
I have the same issue on a Synology Diskstation after a hombridge docker container update and restore of previous homebridge installation:

USER: root
DIR: /var/lib/homebridge
CMD: npm install --save homebridge-synology@latest

npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/homeinstalator/syno.git
npm ERR! No user exists for uid 1028
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/homebridge/.npm/_logs/2022-06-25T14_12_51_539Z-debug-0.log

Operation failed. Please review log for details.

Seems that it is a problem with access rights but I don't know how to handle.

**Comment by stfnhmplr** [comment]
There's a workaround in #85.
