### ISSUE TITLE
Plugin appears to come up and connect but temperature sensors read 0

### ISSUE THREAD

**Issue by tmwong2003** [stfnhmplr/homebridge-synology#77]
**Describe The Bug:**

I am trying to setup the `homebridge-synology` plugin to connect to a Synology DS420j running DSM 7.1-42661 Update 3. The plugin comes up, but the accessories appear with the Synology powered off and zero-value temperatures. I know the Synology is up, because my `homebridge` is running on the Synology itself.

**To Reproduce:**

1. Create a dedicated administrative account on the Synology.
1. Disable auto-block (#59).
1. Configure `homebridge-synology` as shown in the config below.

**Expected behavior:**

- Diskstation plugin power button is on
- Temperature gauges read above 0º C.

**Logs:**

Using `egrep "ynology|isk" homebridge.log`:

```
[8/21/2022, 5:29:31 PM] Loaded plugin: homebridge-synology@0.5.0
[8/21/2022, 5:29:31 PM] Registering accessory 'homebridge-synology.synology'
[8/21/2022, 5:29:31 PM] [DiskStation] Initializing synology accessory...
[8/21/2022, 5:29:31 PM] [DiskStation] Synology DiskStation finished initializing!
2022-08-22T00:29:34.538Z HAP-NodeJS:Accessory [Homebridge FD4A CAD2] Got Characteristic "Manufacturer" value: "Synology"
2022-08-22T00:29:34.538Z HAP-NodeJS:Accessory [Homebridge FD4A CAD2] Got Characteristic "Model" value: "Diskstation"
2022-08-22T00:30:01.977Z HAP-NodeJS:Accessory [DiskStation] Muting event notification for Status Active as ids aren't yet assigned!
2022-08-22T00:30:01.979Z HAP-NodeJS:Accessory [DiskStation] Muting event notification for Status Active as ids aren't yet assigned!
2022-08-22T00:30:05.243Z HAP-NodeJS:Accessory [Homebridge FD4A CAD2] Got Characteristic "Manufacturer" value: "Synology"
2022-08-22T00:30:05.244Z HAP-NodeJS:Accessory [Homebridge FD4A CAD2] Got Characteristic "Model" value: "Diskstation"
```

**Plugin Config:**

```json
    {
            "name": "DiskStation",
            "host": "127.0.0.1",
            "mac": "90-09-D0-09-EA-6F",
            "port": 5001,
            "username": "[REDACTED]",
            "password": "[REDACTED]",
            "protocol": "https",
            "version": "6.2.2",
            "startupTime": 60,
            "shutdownTime": 60,
            "accessory": "synology"
     }
```

**Screenshots:**
![Screen Shot 2022-08-21 at 5 50 50 PM](https://user-images.githubusercontent.com/4977785/185819242-b5a75ffa-9abb-4e01-bf15-ecd3443c270b.png)

**Environment:**

* **Plugin Version**: `homebridge-synology v0.5.0`
* **Homebridge Version**: 1.5.0
* **Node.js Version**: v16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Synology DSM 7.1-42661 Update 3

<!-- Click the "Preview" tab before you submit to ensure the formatting is correct. -→

**Comment by ocager** [comment]
I confirm to have the same issue (as reported by many others in the Issues section). Hope there will be a comment / solution soon available.

**Comment by romanr** [comment]
> I confirm to have the same issue (as reported by many others in the Issues section). Hope there will be a comment / solution soon available.

Same problem here. Do you have it on https and local network? I think it may be not working because of self-signed certificate not being allowed.

**Comment by tmwong2003** [comment]
Switched the plugin config such that `"protocol": "http"` and `"port": 5000`, but now I see a different error in the log:
```
[9/29/2022, 11:36:18 AM] [DiskStation] Device is not online; Polling temperature disabled.
[9/29/2022, 11:36:18 AM] [DiskStation] Device is not online; Polling disk temperature disabled.
```
The Synology is online since it is hosting the HomeBridge. If this was an authentication issue between the plugin and the Synology would I see a different error?

I tried setting `"host"` to either `"127.0.0.1"` (i.e., `localhost`) or the actual IP address of the Synology, but still see the "Device is not online" error.

**Comment by mames13** [comment]
Hi, Did you guys figure this out. I'm having the same problem. My Homebridge is hosted on a DS120j running 7.0.1. I have one other DS running 7.0.1 and one running 7.1. All three appear to be offline /off when they are not. I did try this plugin on a test Homebridge about 2 weeks ago and it seemed to be working fine so I suspect it is a Synology problem. Would love to get this working.

**Comment by nh13** [comment]
The `ping` module used by this plugin routes its request to the underlying `ping` command line utility.  Running `ping <ip address>` in the terminal gives me the error: `ping: socket: Operation not permitted`.  This lead me to looking [here](https://superuser.com/questions/1702163/ping-socket-operation-not-permitted-ubuntu-docker-image).  

The solution was to separately log into the DiskStation via ssh and execute `sudo setcap 'cap_net_raw+ep' "$(which ping)"`.  Then restart HomeBridge and voila, it can now ping the DiskStation and operate normally.

**Comment by tmwong2003** [comment]
The workaround cited in #86 to enable `ping` works, and I can now see temperatures. While I agree that requiring the end user to `ssh` into the DiskStation is not ideal, it does work.

I'll leave this issue open while I look at the code to see if one can eliminate the dependency on `ping`.

![Screenshot 2023-01-30 at 8 23 27 PM](https://user-images.githubusercontent.com/4977785/215665918-d594bf9b-ba30-4bcb-b6bb-141c4cb4d72b.png)

**Comment by tmwong2003** [comment]
Well, that was embarrassing... ignore that password (which thankfully was the now-changed password for the non-admin account).

![215665999-953bec3f-7891-4fc5-a2bc-8f0ff2c84a0d](https://user-images.githubusercontent.com/4977785/215670227-7394ea06-d557-4efa-b69c-52eee80fe88a.png)
