### ISSUE TITLE
Installition: errno -4058

### ISSUE THREAD

**Issue by PayneBLADE** [stfnhmplr/homebridge-synology#80]
Try to install from Homebridge

npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent An unknown git error occurred
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2022-10-30T17_34_54_081Z-debug-0.log

Operation failed. Please review log for details.

---

LOG:

88 verbose Windows_NT 10.0.22621
89 verbose node v16.18.0
90 verbose npm  v8.19.2
91 error code ENOENT
92 error syscall spawn git
93 error path git
94 error errno -4058
95 error enoent An unknown git error occurred
96 error enoent This is related to npm not being able to find a file.
96 error enoent
97 verbose exit -4058
98 timing npm Completed in 2660ms
99 verbose unfinished npm timer reify 1667151294170
100 verbose unfinished npm timer reify:loadTrees 1667151294175
101 verbose code -4058
102 error A complete log of this run can be found in:
102 error     C:\Windows\system32\config\systemprofile\AppData\Local\npm-cache\_logs\2022-10-30T17_34_54_081Z-debug-0.log

**Comment by mames13** [comment]
Hi, I believe I have the same kind of error. Where you every able to figure out a solution? Thanks!

**Comment by mames13** [comment]
Did you try installing GIT Server in Package Center? That should fix this problem.

**Comment by stfnhmplr** [comment]
depending on your setup the workaround from #85 could be a solution. To install this plugin you need git.
