### ISSUE TITLE
Homebridge completely restarting when Synology not reachable after update to v0.5.1

### ISSUE THREAD

**Issue by kolorfilm** [stfnhmplr/homebridge-synology#89]
**Describe The Bug:**
Once I updated the plug-in to the latest version, my homebridge constantly restarting when my synology is off. Normally my synology is off in the night and starting in the morning.

It did not happen before the plug-in update. v0.5.0 just working fine.

**To Reproduce:**
Update to latest version. Shutdown synology.

**Expected behavior:**
Homebridge should work also when synology not reachable.

**Screenshots:**

![2364B35D-EF9F-4163-9215-569722490B9C](https://user-images.githubusercontent.com/26705027/222885412-ac91c76e-4b5e-4537-a78c-0cfe19bc84b7.jpeg)

**Environment:**

* **Plugin Version**: homebridge-synology v0.5.1
* **Homebridge Version**: v1.6.0
* **Node.js Version**: v18.14.2
* **NPM Version**: 9.5.0
* **Operating System**: Raspbian

**Comment by stfnhmplr** [comment]
fixed with 1e59af8

**Comment by kolorfilm** [comment]
> fixed with [1e59af8](https://github.com/stfnhmplr/homebridge-synology/commit/1e59af85f565c91453b1e9c79d9f85252c3d86eb)

Wow that was fast. 🚀 Seems to work now. Thanks 🙏
