### ISSUE TITLE
Not getting any reading

### ISSUE THREAD

**Issue by moccajava33** [stfnhmplr/homebridge-synology#9]
Hi,

I can see the device from Eve app.
But all the states are showing 0.

Temp: 0 degrees
Power: OFF
CPU Load: 0%
Disk Usage: 0%

Anything I did wrong?

Config.json:
        {
            "accessory": "Synology",
            "name": "Storage",
            "ip": "192.x.x.x",
            "mac": "00-11-22-33-44-55",
            "port": "5000",
            "secure": true, <--- should i let it remain to false? changed assume coz my DSM login is https
            "account": "admin",
            "password": "somepassword",
            "version": 6
        },

**Comment by stfnhmplr** [comment]
Hi,

I think it is the wrong port. if you have not changed the settings at your diskstation you don't need to set the port number in your config.json. if you use https it should be port 5001.

so try this please:
{
"accessory": "Synology",
"name": "Storage",
"ip": "192.x.x.x",
"mac": "00-11-22-33-44-55",
"secure": true,
"account": "admin",
"password": "somepassword",
"version": 6
},
