### ISSUE TITLE
Support version 7.2

### ISSUE THREAD

**Issue by Nikoxtw** [stfnhmplr/homebridge-synology#92]
Hello, j'aimerais Savoir si une mise a jours et prévue pour fonctionner avec la nouvelle version 7.2 de synology.

D'avance merci

**Comment by JounQin** [comment]
```log
[11/18/2023, 12:29:41 AM] [JounQin - DS] Can't get temperature, Error: Api version: 7.2.1 is not available. Available versions are: 5.0, 5.1, 5.2, 6.0, 6.0.1, 6.0.2, 6.0.3, 6.1, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.5, 6.1.6, 6.1.7, 6.2, 6.2.1, 6.2.2, 6.2.3
```

**Comment by JounQin** [comment]
Blocked by upstream, see also https://github.com/kwent/syno/issues/72

**Comment by stfnhmplr** [comment]
> Hello, j'aimerais Savoir si une mise a jours et prévue pour fonctionner avec la nouvelle version 7.2 de synology.
> 
> D'avance merci

English please. As described in the ReadMe, for versions greater than 6.2.2, specify 6.2.2 anyway. Most things have remained the same.

**Comment by kwent** [comment]
FYI — the upstream blocker (https://github.com/kwent/syno/issues/72) has been resolved. `syno` v3.0.0 now fully supports DSM 7.x with 778 real API definitions extracted from official Synology SPK packages.

https://github.com/kwent/syno/releases/tag/v3.0.0
